### ISSUE TITLE
Hörmann HCP

### ISSUE THREAD

**Issue by riogrande75** [Bouni/bwt-rest-sensor#2]
Danke fürs ReAktivieren des Links & Sorry, dass ich nochmal auf diesem Weg lästig sein muss. Hab aber keine andere Möglichkeit gesehen, dich sonst zu kontaktieren.
Darf ich fragen, wie der aktuelle Stand der Hörmann HCP Protokoll Geschichte ist?
Möchte einen ESP direkt über RS485 mit dem Garagentor-Steuerung kommunizieren lassen.
Hast du schon fertige Codeschnipsel, welche ich verwenden dürfte?
Ein eigenes Repo für den Code hast du ja nicht, oder?

**Comment by riogrande75** [comment]
Gave up on this.

**Comment by Bouni** [comment]
@riogrande75 Send me an E-Mail to bouni@owee.de, we can have a conversation then if you want to.
